---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.119.142
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_python_interpreter: python3
